language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eliasdabbas
  password:
    secure: BAYh8qelpJ2Ev+PgC9JuP+nXe+v2wolpQSyZiMBDnUVo0Ge1gJETqKczyykyIP21aJOHcGrIP2DqcssfIJxEDcOV+Sg5kycEksli+7WU1CGeTOHQ39TZcHN7us0U9PxytANE/y8re3sHL7gxFwal4zgWcSBBHdAoV1D7Wo/E3uDNuzlcz0f9nJXESxWDj0geTB33uFKqtUfeWArnfqBfkpUbiP9fTv6lezGr7USmSOJFgqt/ji6xH9GqvoaNfmpMzW0ddYaIfSxB9r/PZ2gmAkY1NnVu+JXW5M038eoZensd9GakCCs2x76HCt6J2MfkSvmfz66QtKe2dqu73taoH8T0tC57JDbVxCs14p/sadwQyborWD0R0XLX530qyI92MP0zNpdXOUSoJGabWOK1B/DmN5wo8ZLkXbAgME2MgsbpuhdiU87N1hITtMzplJv8GjEIUf3jG1UOsh0PvNIvyon2SWXBOsdMcxbj0DPaUmRlWEnGhs2Q10B0qZhDB18YDnbcezpfq2N+FJHHXiz8o0JKPdGzNo22dJ0UQgWuSiNEu9/UA9XtbLCcDqbEFM2P8QUIYNGbeliInGXXyawD1GqGa4FXdyQPz6WKIytIwX8CFU4F6L+3YK26mvIVPz9U7kl7X3Yhc3DVjXL2Q0mo0F6+ZaV+ibXFy/JlRQWFSq8=
  on:
    tags: true
    repo: eliasdabbas/dayiwasborn
    python: 3.6
